<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Payments\Services\" />
    <Folder Include="Sellers\Queries\GetById\" />
    <Folder Include="Sellers\Queries\GetBySlug\" />
    <Folder Include="Shippings\DTOs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BazaR.Backend.Domain\BazaR.Backend.Domain.csproj" />
  </ItemGroup>

</Project>
