// <auto-generated />
using System;
using BazaR.Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BazaR.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212105408_InitialCreate5")]
    partial class InitialCreate5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BazaR.Backend.Domain.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Catalog.Attributes.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer")
                        .HasColumnName("value_type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_definitions_code");

                    b.ToTable("attribute_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_attribute_definitions_code_not_empty", "char_length(code) > 0");

                            t.HasCheckConstraint("ck_attribute_definitions_name_not_empty", "char_length(name) > 0");
                        });
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Catalog.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at");

                    b.Property<Guid?>("HiddenBy")
                        .HasColumnType("uuid")
                        .HasColumnName("hidden_by");

                    b.Property<string>("HiddenReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hidden_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerSellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_seller_id");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vendor_code");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_products_barcode");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("OwnerSellerId")
                        .HasDatabaseName("ix_products_owner_seller_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_products_status");

                    b.HasIndex("OwnerSellerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_products_owner_slug")
                        .HasFilter("slug IS NOT NULL");

                    b.HasIndex("OwnerSellerId", "VendorCode")
                        .IsUnique()
                        .HasDatabaseName("ux_products_owner_vendor_code")
                        .HasFilter("vendor_code IS NOT NULL");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_hidden_fields", "(status <> 3) OR (hidden_at IS NOT NULL AND hidden_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_products_name_not_empty", "char_length(name) > 0");

                            t.HasCheckConstraint("ck_products_status_valid", "status IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Catalog.Products.ProductAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean")
                        .HasColumnName("bool_value");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("numeric")
                        .HasColumnName("number_value");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<string>("TextValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text_value");

                    b.Property<Guid>("product_id")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_product_attribute_values_attribute_id");

                    b.HasIndex("product_id")
                        .HasDatabaseName("ix_product_attribute_values_product_id");

                    b.HasIndex("product_id", "AttributeId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_attribute_values_product_attribute");

                    b.ToTable("product_attribute_values", (string)null);
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.HasIndex("ParentCategoryId", "SortOrder")
                        .HasDatabaseName("ix_categories_parent_sort");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_name_not_empty", "char_length(name) > 0");

                            t.HasCheckConstraint("ck_categories_sort_order_non_negative", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Categories.CategoryAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_filterable");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("SectionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section_name");

                    b.Property<int?>("SectionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("section_order");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("category_id")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_category_attributes_attribute_id");

                    b.HasIndex("category_id")
                        .HasDatabaseName("ix_category_attributes_category_id");

                    b.HasIndex("category_id", "AttributeId")
                        .IsUnique()
                        .HasDatabaseName("ux_category_attributes_category_attribute");

                    b.ToTable("category_attributes", null, t =>
                        {
                            t.HasCheckConstraint("ck_category_attributes_section_order_non_negative", "section_order IS NULL OR section_order >= 0");

                            t.HasCheckConstraint("ck_category_attributes_sort_order_non_negative", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Sales.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_offers_product_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_offers_seller_id");

                    b.HasIndex("ProductId", "SellerId")
                        .IsUnique()
                        .HasDatabaseName("ux_offers_product_id_seller_id");

                    b.HasIndex("ProductId", "Status")
                        .HasDatabaseName("ix_offers_product_id_status");

                    b.ToTable("offers", null, t =>
                        {
                            t.HasCheckConstraint("ck_offers_price_amount_non_negative", "price_amount IS NULL OR price_amount >= 0");

                            t.HasCheckConstraint("ck_offers_price_currency_len", "price_currency IS NULL OR char_length(price_currency) = 3");

                            t.HasCheckConstraint("ck_offers_stock_non_negative", "stock >= 0");
                        });
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Sellers.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastDecisionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_decision_at");

                    b.Property<Guid?>("LastDecisionBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_decision_by");

                    b.Property<string>("LastRejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("last_rejection_reason");

                    b.Property<string>("LegalName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SuspensionReason")
                        .HasColumnType("text")
                        .HasColumnName("suspension_reason");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tax_number");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_sellers_owner_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sellers_status");

                    b.HasIndex("TaxNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_sellers_tax_number")
                        .HasFilter("tax_number IS NOT NULL");

                    b.ToTable("sellers", null, t =>
                        {
                            t.HasCheckConstraint("ck_sellers_name_not_empty", "char_length(name) > 0");

                            t.HasCheckConstraint("ck_sellers_slug_not_empty", "char_length(slug) > 0");
                        });
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("_roles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Carts.Cart", b =>
                {
                    b.OwnsMany("BazaR.Backend.Domain.Carts.CartItem", "_items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("cart_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("cart_id", "ProductId")
                                .IsUnique();

                            b1.ToTable("cart_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("cart_id");

                            b1.OwnsOne("BazaR.Backend.Domain.Common.Money", "PriceSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("CartItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_currency");

                                    b2.HasKey("CartItemId");

                                    b2.ToTable("cart_items");

                                    b2.WithOwner()
                                        .HasForeignKey("CartItemId");
                                });

                            b1.Navigation("PriceSnapshot")
                                .IsRequired();
                        });

                    b.Navigation("_items");
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Catalog.Attributes.AttributeDefinition", b =>
                {
                    b.OwnsMany("BazaR.Backend.Domain.Catalog.Attributes.AttributeOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("attribute_definition_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer")
                                .HasColumnName("sort_order");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("value");

                            b1.HasKey("attribute_definition_id", "Id");

                            b1.HasIndex("attribute_definition_id", "Value")
                                .IsUnique()
                                .HasDatabaseName("ux_attribute_options_definition_value");

                            b1.ToTable("attribute_options", null, t =>
                                {
                                    t.HasCheckConstraint("ck_attribute_options_sort_order_non_negative", "sort_order >= 0");

                                    t.HasCheckConstraint("ck_attribute_options_value_not_empty", "char_length(value) > 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("attribute_definition_id");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Catalog.Products.ProductAttributeValue", b =>
                {
                    b.HasOne("BazaR.Backend.Domain.Catalog.Products.Product", null)
                        .WithMany("AttributeValues")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Categories.CategoryAttribute", b =>
                {
                    b.HasOne("BazaR.Backend.Domain.Categories.Category", null)
                        .WithMany("Attributes")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Orders.Order", b =>
                {
                    b.OwnsOne("BazaR.Backend.Domain.Orders.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apartment")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("apartment");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("BazaR.Backend.Domain.Orders.OrderItem", "_items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("order_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("order_id", "ProductId");

                            b1.ToTable("order_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("order_id");

                            b1.OwnsOne("BazaR.Backend.Domain.Common.Money", "PriceSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_currency");

                                    b2.HasKey("OrderItemId");

                                    b2.ToTable("order_items");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId");
                                });

                            b1.Navigation("PriceSnapshot")
                                .IsRequired();
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("_items");
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Sales.Offer", b =>
                {
                    b.OwnsOne("BazaR.Backend.Domain.Common.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("OfferId");

                            b1.ToTable("offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.Navigation("Price");
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Sellers.Seller", b =>
                {
                    b.OwnsOne("BazaR.Backend.Domain.Sellers.CountryCode", "CountryCode", b1 =>
                        {
                            b1.Property<Guid>("SellerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.HasKey("SellerId");

                            b1.ToTable("sellers");

                            b1.WithOwner()
                                .HasForeignKey("SellerId");
                        });

                    b.OwnsOne("BazaR.Backend.Domain.Sellers.EmailAddress", "SupportEmail", b1 =>
                        {
                            b1.Property<Guid>("SellerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("support_email");

                            b1.HasKey("SellerId");

                            b1.ToTable("sellers");

                            b1.WithOwner()
                                .HasForeignKey("SellerId");
                        });

                    b.OwnsOne("BazaR.Backend.Domain.Sellers.SellerSlug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("SellerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("slug");

                            b1.HasKey("SellerId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ux_sellers_slug");

                            b1.ToTable("sellers");

                            b1.WithOwner()
                                .HasForeignKey("SellerId");
                        });

                    b.OwnsOne("PhoneNumber", "SupportPhone", b1 =>
                        {
                            b1.Property<Guid>("SellerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("support_phone");

                            b1.HasKey("SellerId");

                            b1.ToTable("sellers");

                            b1.WithOwner()
                                .HasForeignKey("SellerId");
                        });

                    b.Navigation("CountryCode")
                        .IsRequired();

                    b.Navigation("Slug")
                        .IsRequired();

                    b.Navigation("SupportEmail");

                    b.Navigation("SupportPhone");
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Users.User", b =>
                {
                    b.OwnsOne("BazaR.Backend.Domain.Users.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Catalog.Products.Product", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("BazaR.Backend.Domain.Categories.Category", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
